---
  - name: Enable RDP
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
      name: 'fDenyTSConnections'
      data: '0'
      type: dword

  - name: Enable RDP Firewall Rules
    win_firewall_rule:
     name: "Remote Desktop (Created by Ansible)"
     localport: 3389
     action: allow
     protocol: tcp
     direction: in
     state: present
     enabled: yes
     profiles: 'domain,public,private'