---
- name: Converge
  hosts: all
  roles:
    - role: enablerdp
  vars:
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_port: 55986
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_scheme: https
